# Generated by Django 4.2.5 on 2023-10-02 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(upload_to='')),
                ('small_description', models.TextField(max_length=500)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=500)),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='0=default,1=Trending')),
                ('trending', models.BooleanField(default=False, help_text='0=default,1=Trending')),
                ('tag', models.CharField(max_length=150)),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_keywords', models.CharField(max_length=150)),
                ('meta_description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
    ]
